### PR TITLE
Allow Previewing of future posts option

### PR DESCRIPTION
**Pull request by jess**

### CODE REVIEW

**Comment by jasoncodes** [comment]
This will be a nice feature and the code looks great. Thanks.

A few tweaks to the README copy, if I may:

“only select posts that are dated before the current date” is incorrect. Postmarkdown includes posts dated today. Maybe something like the following?

> By default, Postmarkdown will only show posts that are dated on or before today.

The example of using a generator and the URL the resulting post is available at does not really add anything useful. It’s essentially a duplication of the “Generate a new Post” section. Perhaps something like the following could replace everything after the configuration example?

> With the `:allow_preview` option set, you'll be able to view individual posts by their URL but they will remain hidden from the index and feed until the post date.

**Comment by jess** [comment]
Thanks!

On the example of using the generator, I think I was trying to be too detailed in giving the example of how to access the show route, but I imagine the typical user is a developer and will easily realize how to access the post.

Suggestions sound good to me.

**Comment by jasoncodes** [comment]
Merged and released. Thanks!

**Comment by jess** [comment]
Thanks for all your help!

**Pull request merged**
