### PR TITLE
Allow setting the specific layout name.

### PR DESCRIPTION
**Pull request by lazyatom**
In an application, I might want to use an existing layout which
isn't called `application` or `postmarkdown`.

### CODE REVIEW

**Comment by jasoncodes** [comment]
I am wondering if we should move to `:theme` but leave `:use_theme` around for backwards compatibility. The docs would only mention `:theme`. We can then remove `:use_theme` at a later time when appropriate. I see no semantic issues with `:theme => true` using the built-in theme.

**Comment by twe4ked** [comment]
Sounds good to me.

**Comment by jasoncodes** [comment]
Thinking about this some more, maybe we should go with something like `:layout` as the new name. Potentially we could also have `options[:layout] = 'postmarkdown'` as a replacement for `options[:use_theme] = true`.

**Comment by lazyatom** [comment]
`:layout` sounds good to me.

**Comment by lazyatom** [comment]
I've reworked the commit in line with suggestions above.

**Comment by jasoncodes** [comment]
Looking good. Thanks for the pull request.

FYI I have deprecated the `:use_theme` option as a part of this merge.

This addition is now available in [0.0.5](https://rubygems.org/gems/postmarkdown/versions/0.0.5).

**Pull request merged**
