### PR TITLE
Updated engine for Rails 3.1 compatibility

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
Updated for Rails 3.1, fixed view path issue which prevented overrides working and increased version number.

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
How about a merge yo?

**Comment by twe4ked** [comment]
Pulled in your `append_view_path` change here ef16db57401f1650df8ed9189d53e0d970969268 and added some tests here 90312755ef4ca9ae85a2eb42dbde1e56718121d6.

@jasoncodes is working on a way to move the assets but keep 3.0 compatibility with tests. Thanks for working out the 3.1 way.

**Comment by ivanvanderbyl** [comment]
Thanks dude, I think there is a few more changes on my branch, I did some other customisations within testpilot, but it's working nicely here [http://beta.testpilot.me/blog](http://beta.testpilot.me/blog)

**Comment by twe4ked** [comment]
Blog looks great :)

**Comment by jasoncodes** [comment]
I have added support for the Rails 3.1 asset pipeline eafba9662221c8946855edea2bc5ea874c62e525 and made the relevant test more generic 3969436d23b0f7be3fcb72e09d731397d744a8a1 to handle the varying stylesheet request path.

**Comment by jasoncodes** [comment]
Postmarkdown 0.0.2 has been released with Rails 3.1 support.

**Pull request closed without merging**
